
#define DBG_LEVEL_WARNING 0x0
#define DBG_LEVEL_ERROR 0x1
#define DBG_LEVEL_FATAL 0x2
#define CONSOLE_INPUT_LINE_BUFFER_SIZE 128
#define CONSOLE_DEFAULT_LABEL "Console"
#define DEFAULT_RESOURCES_FOLDER "Resources"
